Areas/Admin/Controllers/CameronController.cs
using System.Security.Claims;
using etherapist.Data;
using etherapist.Models;
using etherapist.Models.ViewModels;
using etherapist.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Threading.Tasks;

using Quartz;
using Quartz.Impl;
using Microsoft.AspNetCore.Authorization;

namespace etherapist.admin.controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]
public class CameronController: Controller {
    private readonly ApplicationDbContext _db;

    public CameronController(ApplicationDbContext db) {
        _db = db;
    }

    public IActionResult Index(String testType) {
        List<CameronTest> tests;

        if (testType == SD.testQE || testType == SD.testIAndS ||testType == SD.testBT ) {
            tests = _db.CameronTests.Where(test => test.TestType == testType)
                .ToList();
        }
        else {
            tests = _db.CameronTests.ToList();
        }
        
        return View(tests);
    }
}

Areas/Admin/Controllers/SessionsController.cs
using System.Security.Claims;
using etherapist.Data;
using etherapist.Models;
using etherapist.Models.ViewModels;
using etherapist.Utility;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Threading.Tasks;

using Quartz;
using Quartz.Impl;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace etherapist.admin.controllers;
[Area("Admin")]
[Authorize(Roles = SD.Role_Admin)]

public class SessionsController: Controller {
    private readonly ApplicationDbContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public SessionsController(ApplicationDbContext db, UserManager<ApplicationUser> userManager ) {
        _db = db;
        _userManager = userManager;
    }

    public IActionResult Index(String status) {
        List<Session> sessions;

        if (status == "processing") {
            sessions = _db.Sessions.Where(
                session => session.Status <= SD.session_awaitingTherapistAssign
                ).Include("Patient").Include("Therapist").ToList();
        }
        else if (status == "approved") {
            sessions = _db.Sessions.Where(
                session => session.Status == SD.session_awaitingTherapistApproval
                ).Include("Patient").Include("Therapist").ToList();
        }
        else if (status == "completed") {
            sessions = _db.Sessions.Where(
                session => session.Status >= SD.session_sessionCompleted
                ).Include("Patient").Include("Therapist").ToList();
        }
        else {
            sessions = _db.Sessions.Where(
                session => session.Status >= SD.session_awaitingTherapistAssign
                ).Include("Patient").Include("Therapist").ToList();
        }

        return View(sessions);
    }

    public IActionResult Details(Int32 sessionId) {
        Session? patientSession = _db.Sessions
            .Include("Patient").Include("Therapist")
            .FirstOrDefault(session => session.Id == sessionId);
            
        List<SelectListItem> therapists = _userManager.GetUsersInRoleAsync(SD.Role_Therapist)
            .GetAwaiter().GetResult()
            .Select(therapist => new SelectListItem{Text=$"{therapist.FirstName} {therapist.LastName}", Value=therapist.Id})
            .ToList();

        SessionVM sessionVm = new() {
            session = patientSession,
            therapists = therapists
        };

        return View(sessionVm);
    }

    [HttpPost]
    public IActionResult Details(SessionVM sessionVm) {
        Session? patientSession = _db.Sessions
            .Include("Patient").Include("Therapist")
            .FirstOrDefault(session => session.Id == sessionVm.session.Id);

        if (patientSession.TherapistId != null) {
            sessionVm.session = patientSession;
            TempData["error"] = "A therapist has been assigned to this patient";
            return View(sessionVm);
        }

        patientSession.TherapistId = sessionVm.session.Therapist.Id;
        patientSession.Status = SD.session_awaitingTherapistApproval;
        _db.SaveChanges();

        TempData["success"] = "Therapist successfully assigned";
        return RedirectToAction(nameof(Index));
    }

    public IActionResult History () {
        return View();
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using etherapist.Utility

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - etherapist</title>
    <link rel="stylesheet" href="https://cdn.metroui.org.ua/v4.3.2/css/metro-all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/etherapist.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @if (SignInManager.IsSignedIn(User)) {
            if (User.IsInRole(SD.Role_Patient)){
                <!-- Nav bar: Patient -->
                <partial name="_NavbarPatient" />
                <!-- Sidebar: Patient -->
                <partial name="_SidebarPatient" />
            }
            else if (User.IsInRole(SD.Role_Admin)) {
                <!-- Nav bar: Admin -->
                <partial name="_NavbarAdmin" />
                <!-- Sidebar: Admin -->
                <partial name="_SidebarAdmin" />
            }
            else {
                <!-- Nav bar: Therapist -->
                <partial name="_NavbarTherapist" />
                <!-- Sidebar: Therapist -->
                <partial name="_SidebarTherapist" />
            }
        }
        else {
            <!-- Nav bar -->
            <partial name="_NavbarHome" />
        }

    </header>
        <main role="main" class="pb-3">
            <div class="container-fluid row px-0 py-0">
                <partial name="_Notifications" />
                @RenderBody()
            </div>
        </main>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - etherapist - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.metroui.org.ua/v4.3.2/js/metro.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script type="text/javascript">
        $(function () {
            var page = sessionStorage.getItem('page');
            var sidebar = document.querySelectorAll('.c-sidebar-item');

            if (page == null) {
                $(sidebar[0]).addClass('active');
            } else {
                sidebar.forEach((item, index) => {
                    if (item.href == page) {
                        $(item).addClass('active').siblings().removeClass('active');
                        console.log(item.href)
                    }
                });
            }
        })

        $(document).on('click', '.c-sidebar-item', function () {
            var x = this.href;
            console.log(this)
            window.stop()
            sessionStorage.setItem('page', x);
        });
    </script>
</body>
</html>

Views/Shared/_NavbarAdmin.cshtml
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <div class="container-fluid mx-5">
        <!-- Logo -->
        <a class="navbar-brand text-white me-5" style="font-weight:500" asp-area="Admin" asp-controller="Sessions" asp-action="Index">
            ETherapist
        </a>
        <a class="nav-link dropdown-toggle" style="font-size:12px" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            CMT
        </a>
        <ul class="dropdown-menu dropdown-menu-dark">
            <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a></li>
        </ul>
        <!-- Sign Up or Log in -->
        <div class="d-flex" style="font-size:12px;margin-left:auto">
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

Views/Shared/_NavbarHome.cshtml
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <div class="container-fluid mx-5">
        <!-- Logo -->
        <a class="navbar-brand text-white" style="font-weight:500" asp-controller="Home" asp-action="Index">
            ETherapist
        </a>
        <!-- Sign Up or Log in -->
        <div class="d-flex" style="font-size:12px;margin-left:auto">
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

Views/Shared/_NavbarPatient.cshtml
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <div class="container-fluid mx-5">
        <!-- Logo -->
        <a class="navbar-brand text-white" style="font-weight:500" asp-area="Patient" asp-controller="Sessions" asp-action="Index">
            ETherapist
        </a>
        <!-- Sign Up or Log in -->
        <div class="d-flex" style="font-size:12px;margin-left:auto">
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

Views/Shared/_NavbarTherapist.cshtml
<nav class="navbar navbar-expand-md navbar-dark bg-primary fixed-top">
    <div class="container-fluid mx-5">
        <!-- Logo -->
        <a class="navbar-brand text-white" style="font-weight:500" asp-area="Therapist" asp-controller="Sessions" asp-action="Index">
            ETherapist
        </a>
        <!-- Sign Up or Log in -->
        <div class="d-flex" style="font-size:12px;margin-left:auto">
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>

Views/Shared/_Notifications.cshtml
@if (TempData["success"] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}

@if (TempData["error"] != null) {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
} 

Views/Shared/_SidebarAdmin.cshtml
<div class="col-3 c-sidebar c-sidebar-shadow">
    <!-- Main menu -->
    <div class=" c-sidebar-menu">
        <h1 class="c-sidebar-header" style="margin-top:75px;">Main Menu</h1>
        <div class="c-sidebar-item-list">
        <!-- Sessions -->
            <a class="c-sidebar-item active" asp-area="Admin" asp-controller="Sessions" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-clock-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Sessions
                </span>
            </a>
            <!-- Subscriptions -->
            <a class="c-sidebar-item" asp-area="Admin" asp-controller="Therapists" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-clipboard2-pulse-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Therapists
                </span>
            </a>
            <!-- Cameron -->
            <a class="c-sidebar-item" asp-area="Admin" asp-controller="Cameron" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-robot"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Cameron
                </span>
            </a>
        </div>
    </div>
    <div class="c-sidebar-footer">
        <div style="font-weight:500">
            Etherapist patient dashboard
        </div>
        <div>
            © 2022 All rights reserved
        </div>
    </div>
</div>

Views/Shared/_SidebarPatient.cshtml
<div class="col-3 c-sidebar c-sidebar-shadow">
    <!-- Main menu -->
    <div class=" c-sidebar-menu">
        <h1 class="c-sidebar-header">Main Menu</h1>
        <div class="c-sidebar-item-list">
        <!-- Sessions -->
            <a class="c-sidebar-item active" asp-area="Patient" asp-controller="Sessions" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-clock-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Sessions
                </span>
            </a>
            <!-- Subscriptions -->
            <a class="c-sidebar-item" asp-area="Patient" asp-controller="Subscriptions" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-collection-play-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Subscriptions
                </span>
            </a>
            <!-- Cameron -->
            <a class="c-sidebar-item" asp-area="Patient" asp-controller="Cameron" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-robot"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Cameron
                </span>
            </a>
        </div>
    </div>
    <button class="c-sidebar-action-button">
        <i class="bi bi-calendar2-week-fill"></i>
        @* <svg class="bi" width="32" height="32" fill="white">
            <use xlink:href="bootstrap-icons.svg#calendar2-week-fill"/>
        </svg> *@
        <a asp-area="Patient" asp-controller="Sessions" asp-action="Create" style="text-decoration:none;color:white">
            Create a Session now
        </a>
    </button>
    <div class="c-sidebar-footer">
        <div style="font-weight:500">
            Etherapist patient dashboard
        </div>
        <div>
            © 2022 All rights reserved
        </div>
    </div>
</div>

Views/Shared/_SidebarTherapist.cshtml
<div class="col-3 c-sidebar c-sidebar-shadow">
    <!-- Main menu -->
    <div class=" c-sidebar-menu">
        <h1 class="c-sidebar-header" style="margin-top:75px;">Main Menu</h1>
        <div class="c-sidebar-item-list">
        <!-- Sessions -->
            <a class="c-sidebar-item active" asp-area="Therapist" asp-controller="Sessions" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-clock-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Sessions
                </span>
            </a>
            <!-- Subscriptions -->
            <a class="c-sidebar-item" asp-area="Therapist" asp-controller="Calendar" asp-action="Index">
                <div class="c-sidebar-item-icon">
                    <i class="bi bi-calendar2-fill"></i>
                </div>
                <span class="c-sidebar-item-text">
                    Calendar
                </span>
            </a>
        </div>
    </div>

    <div class="c-sidebar-footer">
        <div style="font-weight:500">
            Etherapist Therapist dashboard
        </div>
        <div>
            © 2022 All rights reserved
        </div>
    </div>
</div>