Models/Subscription.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace etherapist.Models;

public class Subscription {
    [Key]
    public Int32 Id { get; set; } 
    
    [Required]
    public String PlanName { get; set; }
    
    [Required]
    public Int32 Price { get; set; }

    [Required]
    public String Benefits { get; set; }

    [Required]
    public Int32 AvailableSessions { get; set; }
}

Areas/Patient/Controllers/SubscriptionsController.cs
using System.Security.Claims;
using etherapist.Data;
using etherapist.Models;
using etherapist.Models.ViewModels;
using etherapist.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe.Checkout;

namespace etherapist.patient.controllers;
[Area("Patient")]
[Authorize(Roles = SD.Role_Patient)]
public class SubscriptionsController: Controller {
    private readonly ApplicationDbContext _db;

    public SubscriptionsController(ApplicationDbContext db)
    {
        _db = db;
    }

    public IActionResult Index() {
        String userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        List<PatientSubscription> pSubs = _db.PatientSubscriptions
            .Where(pSub => pSub.PatientId == userId && pSub.PaymentStatus == SD.subPaytStatus_success)
            .Include("Subscription").ToList();

        PatientSubscription activeSub;
        if (pSubs.Count == 0) {
            activeSub = null;
        }
        else {
            activeSub = pSubs.FirstOrDefault(sub => sub.Status == SD.subscription_active);
        }

        SubscriptionVM subscriptionVm = new() {
            PSubscriptions = pSubs,
            ActiveSubscription = activeSub,
            Subscriptions = _db.Subscriptions.ToList()
        };

        return View(subscriptionVm);
    }

    public IActionResult Create() {
        SubscriptionVM subscriptionVm = new () {
            Subscriptions = _db.Subscriptions.ToList()
        };
        return View(subscriptionVm);
    }

    [HttpPost]
    public IActionResult Create(Int32 myId) {
        String userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        IEnumerable<Subscription> subs = _db.Subscriptions;
        Subscription sub = subs.First(sub => sub.Id == myId);

        // Create Subscription View model
        SubscriptionVM subscriptionVm = new () {
            PSubscription = new () {
                PatientId = userId,
                Status = SD.subscription_active,
                SubscriptionId = myId,
                SessionsLeft = sub.AvailableSessions,
                PaymentStatus = SD.subPaytStatus_pending
            },
            Subscriptions = subs.ToList()
        };

        // Check if patient has an active subscription
        PatientSubscription? activeSub = _db.PatientSubscriptions
            .FirstOrDefault(pSub => pSub.Status == SD.subscription_active && pSub.PatientId == userId);
        
        if (activeSub != null) {
            TempData["error"] = "You currently have an active subscription";
            return View(subscriptionVm);
        }

        _db.PatientSubscriptions.Add(subscriptionVm.PSubscription);
        _db.SaveChanges();
        

        // Stripe payment
        var domain = "https://localhost:7126";
        var options = new SessionCreateOptions
        {
            LineItems = new List<SessionLineItemOptions>
            {
                new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = sub.Price,
                        Currency = "ngn",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = sub.PlanName,
                        },
                    },
                    Quantity = 1,
                },
            },
            Mode = "payment",
            SuccessUrl = $"{domain}/Patient/Subscriptions/SubscriptionConfirmation?pSubId={subscriptionVm.PSubscription.Id}",
            CancelUrl = $"{domain}/Patient/Subscriptions/Index",
        };

        var service = new SessionService();
        Stripe.Checkout.Session session = service.Create(options);

        subscriptionVm.PSubscription.PaymentSessionId = session.Id;
        subscriptionVm.PSubscription.PaymentIntentId = session.PaymentIntentId;
        _db.SaveChanges();

        Response.Headers.Add("Location", session.Url);
        return new StatusCodeResult(303);

        // TempData["success"] = $"Successfully subscribed to the {sub.PlanName}";
        // return RedirectToAction("Index");
    }

    public IActionResult SubscriptionConfirmation(Int32 pSubId) {
        PatientSubscription pSub = _db.PatientSubscriptions.Find(pSubId);
        var Service = new SessionService();
        Stripe.Checkout.Session paymentSession = Service.Get(pSub.PaymentSessionId);

        if (paymentSession.PaymentStatus == "paid") {
            pSub.PaymentStatus = SD.subPaytStatus_success;
            _db.SaveChanges();
        }

        TempData["success"] = $"Successfully created subscription";
        return RedirectToAction("Index");
    }
}

Areas/Patient/Views/Subscriptions/Create.cshtml
@using etherapist.Models.ViewModels
@model SubscriptionVM

<!-- Main -->
<div class="col bg-grey py-5 mt-5" style="margin-left:25%">
    <!-- Header -->
    <div class="m-auto px-5 py-5 bg-secondary" style="width:90%;border-radius:15px;">
        <div style="font-weight:600;font-size:30px;">
            <a asp-area="Patient" asp-controller="Subscriptions" asp-action="Index">
                <i class="bi bi-arrow-left"></i>
            </a>&nbsp;&nbsp;Choose your plan
        </div>
        <hr />
        <!-- Body -->
        <div class="pt-3 row">
            @foreach(Subscription sub in Model.Subscriptions) {
                <form class="c-sub-card col me-5" method="post" asp-route-myId="@sub.Id">
                    @if (sub.PlanName == "Monthly Plan") {
                        <div id="c-sub-card-recommend">
                            <p style="margin:0px">Recommended</p>
                        </div>
                    }
                    <div class="c-sub-info">
                        <div class="c-sub-name">@sub.PlanName</div>
                        <div class="c-sub-price">@sub.Price NGN</div>
                        <button type="submit" class="c-sub-submit">Choose</button>
                    </div>
                    <div class="c-sub-benefits">
                        @sub.Benefits
                    </div>
                </form>
            }
        </div>
    </div>
</div>

Areas/Patient/Views/Subscriptions/Index.cshtml
@using etherapist.Models.ViewModels
@model SubscriptionVM

<div class="col bg-grey py-5 mt-5" style="margin-left:25%;">
    <!-- Header -->
    <div class="m-auto px-5 py-5 bg-secondary" style="width:80%;border-radius:15px;">
        <div style="font-weight:600;font-size:30px;">
            Subscriptions
        </div>
        <hr />
        <!-- Body -->
        <div class="py-3">
            <!-- Active Subscription -->
            <div>
                <div style="font-size:20px" class="mb-3">
                    Active Subscription
                    <a asp-area="Patient" asp-controller="Subscriptions" asp-action="Create">
                      <i class="bi bi-plus-circle-fill ms-2"></i>  
                    </a>
                </div>
                @if (Model.ActiveSubscription == null) {
                    <div class="py-3 d-flex align-items-center justify-content-center" 
                        style="min-height:15vh;color:#707070">
                        You currently have no subscription, click &nbsp;<a class="link">here</a>&nbsp; to subscribe now
                    </div>
                }
                else {
                    <table class="table table-dark table-striped">
                        <thead>
                            <tr>
                                <th scope="col" style="color:white">Id</th>
                                <th scope="col" style="color:white">Status</th>
                                <th scope="col" style="color:white">Sessions Left</th>
                                <th scope="col" style="color:white">Plan</th>
                            </tr>
                        </thead>
                        <tbody>
                            <th scope="row">@Model.ActiveSubscription.Id</th>
                            <td>@Model.ActiveSubscription.Status</td>
                            <td>@Model.ActiveSubscription.SessionsLeft</td>
                            <td>@Model.Subscriptions[Model.ActiveSubscription.SubscriptionId -1].PlanName</td>
                        </tbody>
                    </table>
                }
            </div>
            <!-- Subscription History -->
            <div>
                <div style="font-size:20px" class="mb-3">
                    Subscription History
                </div>
                @if (Model.PSubscriptions.Count == 0) {
                    <div class="py-3 d-flex align-items-center justify-content-center" 
                        style="min-height:15vh;color:#707070">
                        When you create a subscription, it will be shown here
                    </div>
                }
                else {
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Status</th>
                                <th scope="col">Sessions Left</th>
                                <th scope="col">Plan</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(PatientSubscription pSub in Model.PSubscriptions) {
                                <tr>
                                    <th scope="row">@pSub.Id</th>
                                    <td>@pSub.Status</td>
                                    <td>@pSub.SessionsLeft</td>
                                    <td>@Model.Subscriptions[pSub.SubscriptionId -1].PlanName</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </div>
</div>